# -*- coding: utf-8 -*-
"""articlesAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lsgrvwkq5lpp-PepazsoSRj7fkhWAZeF
"""

from sentence_transformers import SentenceTransformer
import numpy as np
import os
import pdfplumber
from textpreprocess import TextPreprocess

class ArticleAI:
  def __init__(self, usersPDF="No pdf"):
    self.userPDF = usersPDF
    self.encodeModel = SentenceTransformer("all-MiniLM-L6-v2")
    self.textList = []
    self.userFileProcess()

  def userFileProcess(self):
    print("Preparing your PDF for the model to understand...")
    with pdfplumber.open(self.userPDF) as userFile:
        for pageNum, page in enumerate(userFile.pages):
            pageText = page.extract_text()
            if pageText:
                paragraphs = pageText.split("\n\n")
                for paragraph in paragraphs:
                    if paragraph.strip():
                        self.textList.append({
                            "page": pageNum + 1,
                            "text": paragraph.strip()
                        })

    texts = [text["text"] for text in self.textList]
    if not texts:
      raise ValueError("There is no text to be extracted from your pdf")
    self.embeddingTextList = self.encodeModel.encode(texts)
    print("Model is ready to start processing.")

  def model(self, userInput):
    self.checkedUserInput = TextPreprocess(str(userInput))
    self.embeddingUserInput = self.encodeModel.encode(str(self.checkedUserInput))
    normTarget = np.linalg.norm(self.embeddingUserInput)
    normLable = np.linalg.norm(self.embeddingTextList, axis=1)

    cosSim = (np.dot(self.embeddingTextList, self.embeddingUserInput) / (normLable * normTarget))
    highestSim = np.argmax(cosSim)
    if cosSim[highestSim] < 0.28:
      return f"No relative information is found in {self.userPDF}"
    else:
      highestSimText = self.textList[highestSim]
      return highestSimText


if __name__ == "__main__":
  usersPDF = str(input("Enter your pdf name (example.pdf): "))
  if not os.path.exists(usersPDF):
    raise FileNotFoundError("The program could not find the PDF file.")

  pdfmodel = ArticleAI(usersPDF)
  while True:
    userInput = str(input("Enter what you want to search: "))
    if userInput == "":
      print("Empty input is not allowed.")
      continue
    elif userInput.lower() == "quit":
      print("Leaving program...")
      break
    else:
      target = pdfmodel.model(userInput)
      if isinstance(target, str):
         print(target)
      else:
          print("Page:", target["page"])
          print("\nModel:", target["text"])
  print("Done.")

